/*
 * Copyright (c) 2020 GeekStore.
 * All rights reserved.
 */

package io.geekstore.config.asset;

import java.io.IOException;
import java.io.InputStream;

/**
 * The AssetPersistenceStrategy determines how Asset files are physically stored
 * and retrieved.
 *
 * Created on Nov, 2020 by @author bobo
 */
public interface AssetStorageStrategy {
    /**
     * Writes a buffer to the store and returns a unique identifier for that
     * file such as a file path or a URL.
     */
    String writeFileFromBuffer(String fileName, byte[] buffer);

    /**
     * Writes a readable stream to the store and returns a unique identifier for that
     * file such as a file path or a URL.
     */
    String writeFileFromStream(String fileName, InputStream stream) throws IOException;

    /**
     * Reads a file based on an identifier which was generated by a writeFile
     * method, and returns the as a Buffer.
     */
    byte[] readFileToBuffer(String identifier);

    /**
     * Reads a file based on an identifier which was generated by a writeFile
     * method, and returns the file as a Stream.
     */
    InputStream readFileToStream(String identifier);

    /**
     * Deletes a file from the storage.
     */
    void deleteFile(String identifier);

    /**
     * Check whether a file with the given name already exists. Used to avoid
     * naming conflicts before saving the file.
     */
    boolean fileExists(String fileName);


    /**
     * Convert an identifier as generated by the writeFile... methods into an absolute
     * url (if it is not already in that form). If no conversion step is needed
     * (i.e. the identifier is already an absolute url) then this method
     * should not be implemented.
     */
    String toAbsoluteUrl(/* TODO request */ String identifier);
}
